/******************************************************************************/
/****     Generated by IBExpert 2015.12.21.1 06/11/2018 11:29:00 p. m.     ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE '127.0.0.1:C:\app\data\proceso.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;

